// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace PVControl
{
	[Table("hourly")]
	public class Hourly
	{
    [Column("timestamp")] public DateTime Timestamp { get; set; } // text(max)
    [Column("temperatureoutside")] public float? Temperatureoutside { get; set; } // real
    [Column("cloudcover")] public int? Cloudcover { get; set; } // integer
    [Column("humidity")] public int? Humidity { get; set; } // integer
    [Column("pvyield")] public int? Pvyield { get; set; } // integer
    [Column("importenergy")] public int? Importenergy { get; set; } // integer
    [Column("exportenergy")] public int? Exportenergy { get; set; } // integer
    [Column("houseenergy")] public int? Houseenergy { get; set; } // integer
    [Column("batterycharge")] public int? Batterycharge { get; set; } // integer
    [Column("batterydischarge")] public int? Batterydischarge { get; set; } // integer
    [Column("batterysoc")] public int? Batterysoc { get; set; } // integer
    [Column("carcharge")] public int? Carcharge { get; set; } // integer
    [Column("carsoc")] public int? CarSoC { get; set; } // intger
    [Column("cardischarge")] public int? Cardischarge { get; set; } // intger
    [Column("heatpumpenergy")] public int? Heatpumpenergy { get; set; } // integer
    [Column("warmwaterenergy")] public int? Warmwaterenergy { get; set; } // integer
    [Column("priceenergyimport")] public float? Priceenergyimport { get; set; } // real
    [Column("priceenergyexport")] public float? Priceenergyexport { get; set; } // real
    [Column("temperatureinside")] public float? Temperatureinside { get; set; } // real
    [Column("temperaturewarmwater")] public float? Temperaturewarmwater { get; set; } // real
    [Column("atmopressure")] public float? Atmopressure { get; set; } // real
  }
}
